### ISSUE TITLE
Благодарность

### ISSUE THREAD

**Issue by kentr0w** [ddneprov/PocketBusiness#1]
Спасибо

**Comment by kentr0w** [comment]
@ddneprov don't ignore it!

**Comment by ddneprov** [comment]
@kentr0w ЭТО ДЛЯ БОГААТЫХ, НА ВЕДРАХ НЕ РАБОТАЕТ

**Comment by kentr0w** [comment]
@ddneprov I don't understand Ukrainian language. Fix it please. dodik
